  server:
    port: 8080

  spring:
    application:
      name: lgpd
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
      url: jdbc:mysql://localhost:3306/lgpd?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver